---
title: "Worum geht es?"
---

Auf dieser Seite werden (über die kommenden Wochen) fünf verschiedene R-Projekte erscheinen, die dazu da sind, sich auch unabhängig von den Inhalten der Statistik Volesung mit R zu beschäftigen.

Hier sollte dann zusätzlich ein Text entstehen, der das gesamte Vorhaben beschreibt - also Zielgruppe, inhaltliches Ziel bzw. Kompetenzen die hier gelernt werden können, wie man Vorgehen soll etc. Gegebenenfalls sollte das Ganze hier auch in Abschnitte unterteilt werden, damit das hier alles übersichtlich bleibt.


### [Projekt 1: Titel](p1_main.html)

An dieser Stelle sollten die einzelnen Projekte in Abstract-Form kurz dargestellt werden.

### [Projekt 2: Titel](p2_main.html)

An dieser Stelle sollten die einzelnen Projekte in Abstract-Form kurz dargestellt werden.

### [Projekt 3: Titel](p3_main.html)

An dieser Stelle sollten die einzelnen Projekte in Abstract-Form kurz dargestellt werden.

### [Projekt 4: Titel](p4_main.html)

An dieser Stelle sollten die einzelnen Projekte in Abstract-Form kurz dargestellt werden.

### [Projekt 5: Titel](p5_main.html)

An dieser Stelle sollten die einzelnen Projekte in Abstract-Form kurz dargestellt werden.
