---
title: "Datenverarbeitung von Google Trends"
---

Inhaltliche Beschreibung des Projektes.

Wir wissen, dass Google unendlich viele Daten von uns sammelt und speichert. Somit haben sie eine uneingeschränkte Einsicht in unser Gesellschaft. Glücklicherweise geben sie uns einen Krümmel dieses großen Kuches zurück. Denn auf der Seite "Google Trends" lassen sich jegliche Suchbegriffe finden und Statistiken wo und wann sie am meisten gesucht wurden. Aber vertraue natürlich keiner Statstik die du nicht selbst gefälscht hast.

## Zielsetzung

Beschreibung des Ziels im Sinne des Kompetenzerwerbs. Hier geht es noch nicht um die konkrete Inhalte, sondern ausschließlich um das große Ganze, das in dieser Session erreicht werden soll.

In dieser ersten Aufgabe wirst du Grundkompetenzen zu dem Verarbeiten von Datensätzen lernen. Wir zeigen dir mit "ggplot2" Darstellungen zu konstruieren und andere grundsätzliche Fähigkeiten, die du für die folgenden Aufgaben brauchen wirst. Es geht schlussendlich darum eine gute und übersichtliche Aufbereitung der Daten für verschiedene Kontexte zu haben.



## Vorwissen

Hier sollte nötiges Vorwissen behandelt werden, bzw. auf Stellen verlinkt werden, wo das zu finden ist. Mitunter kann es dabei hilfreich sein, schon kleinere Abfragen einzubauen.


Der Link auf dem du die oben beschriebene Seite findest lautet https://trends.google.de/trends/?geo=DE 
Auf der Seite befindet sich ein Suchfeld , wo du den ersten Begriff eingeben und dir seine Statistiken anschauen kannst (bitte gebe als Beispiel einmal Affe ein). 
Nun kannst du andere Begriffe mit dem Beispiel vergleichen (gebe in das Feld "+Vergleichen" Giraffe ein). Du kannst bis zu vier Begriffe vergleichen.
Die Skala ist bei jeder Statistik sehr wichtig und kann fehl interpretiert werden. Daher ist es sehr wichtig, dass du dich mit der Skala dieses Datensatzes befasst. Über jeder Abbildung befindet sich ein <i class="fas fa-question"></i>
Hier wird jeder Punkt im Bezug zum höchsten Punkt dargestellt. Das bedeutet in unserem Beispiel, dass im Januar 2018 die Giraffe den höchsten Punkt erreicht hat und der Affe zum gleichen Zeitpunkt nur 6% dieser Suchanfragen hatte. Damit bekommt die Giraffe zu dem Zeitpunkt den Wert 100 und der Affe den Wert 6. Je noch Bezugspunkt ändern sich also die Werte. Dies ist sehr wichtig, wenn man verschiedene dieser Datensätze vergleichen will. 

Die verschiedenen Datensätze kannst du über das Downloadzeichen oben rechts an jeder Abbildung herrunterladen und in Exel öffnen. Speichere sie bitte immer in dem gleichen Ordner, wo du auch dein R-Skript drin hast.

Ggplot2 basiert auf verschiedenen Ebenen die übereinander gelegt werden. Das bedeutet, dass wir:

  <i class="fas fa-caret-right"></i>  zunächst ein leeres Blatt haben
  
  <i class="fas fa-caret-right"></i> ein kariertes Gitter darüber legen
  
<i class="fas fa-caret-right"></i>  oben drauf unsere Daten dargestellt werden

Um ggplot2 benutzen zu können müsst du dir das passende Package herunterladen und es in deine R Sitzung laden.
Grundlagen zu den Befehlen von ggplot2 findest du auf https://rstudio.com/wp-content/uploads/2015/06/ggplot2-german.pdf
Eine weitere Seite, die dir hilfreich sein könnte, um dein ggplot zu verbessern ist https://mmi.psycho.unibas.ch/r-toolbox/formatierungswerkzeuge.html





## Hilfe und Lösungen

Falls du nicht weiter kommst, kannst du dir kleine Denkanstöße bei unseren <a href="./p1_tips.html">Tipps</a> holen. Wenn du fertig bist kannst du dein Lösung mit unseren <a href="./p1_solu.html">Lösungen</a> vergleichen. Du musst auch nicht immer das gleiche haben, da es oft viele Wege zum Ziel gibt.

